# Generated by Django 3.2.12 on 2022-02-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='instance_new_state',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='instance_state',
            field=models.CharField(editable=False, max_length=64),
        ),
    ]
